pkgname             = "boiler"
output              = "infra/boiler"
[psql]
  dbname = "postgres"
  host   = "postgres"
  port   = 5432
  user   = "postgres"
  pass   = "postgrespassword"
  sslmode = "disable"
  schema = "public"
  blacklist = ["migrations", "other"]
