// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Labels             string
	TaskLabelRelations string
	Tasks              string
	Users              string
}{
	Labels:             "labels",
	TaskLabelRelations: "task_label_relations",
	Tasks:              "tasks",
	Users:              "users",
}
